"""empty message

Revision ID: 79687a0499fc
Revises: f656b5b49569
Create Date: 2024-02-12 16:15:27.272742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79687a0499fc'
down_revision = 'f656b5b49569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_battles_wild_pokemon_pokemons'), 'pokemons', ['wild_pokemon'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_battles_trainer_pokemon_pokemons'), 'pokemons', ['trainer_pokemon'], ['id'])

    with op.batch_alter_table('pokemons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_hp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemons', schema=None) as batch_op:
        batch_op.drop_column('max_hp')

    with op.batch_alter_table('battles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_battles_trainer_pokemon_pokemons'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_battles_wild_pokemon_pokemons'), type_='foreignkey')

    # ### end Alembic commands ###
