"""empty message

Revision ID: f656b5b49569
Revises: 9d961329e162
Create Date: 2024-02-12 15:46:23.690968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f656b5b49569'
down_revision = '9d961329e162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_pokemon', sa.Integer(), nullable=True),
    sa.Column('wild_pokemon', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_battles'))
    )
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('motto', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainers'))
    )
    op.create_table('pokemons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('starting_hp', sa.Integer(), nullable=True),
    sa.Column('attack_name', sa.String(), nullable=True),
    sa.Column('attack_desc', sa.String(), nullable=True),
    sa.Column('attack_damage', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], name=op.f('fk_pokemons_trainer_id_trainers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pokemons'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemons')
    op.drop_table('trainers')
    op.drop_table('battles')
    # ### end Alembic commands ###
